name: Latest YouTube Videos

on:
  schedule:
    - cron: "7,22,37,52 * * * *"
  workflow_dispatch:
  repository_dispatch:
    types:
      - youtube_update

permissions:
  contents: write

concurrency:
  group: latest-youtube-videos-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-readme-with-blog:
    name: Update README with latest YouTube videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: gautamkrishnar/blog-post-workflow@2786e54a01b71aec80a5118c2bd6b5044e842597
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UChoDyFV5T1t9qWymeTz8Gvg"
